# Unix

TARGET =
TARGETEXTENSION = 
OUTFMTS = -DOUTAOUT -DOUTBIN -DOUTELF -DOUTHUNK -DOUTSREC -DOUTTOS -DOUTVOBJ -DOUTMEKASYM

CCOUT = -o 
COPTS = -c -O2 $(OUTFMTS)

LD = $(CC)
LDOUT = $(CCOUT)
LDFLAGS = -lm

RM = rm -f

include make.rules
